# -*- coding: utf-8 -*-
"""House_Price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eE7RGL-CEl0BCSRiYX6ZrQiDGNAyvmdq
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.datasets
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics

"""**Regression based model**
A project is Regression when the output is a continuous numeric value.
Ex: House price prediction , Salary prediction , Temperature prediction , Stock price prediction
"""

# house_price_dataset = sklearn.datasets.load_boston() #load_boston() was removed from scikit-learn.
#Using the California Housing Dataset, which replaced Boston

# from sklearn.datasets import fetch_california_housing

# house_price_dataset = fetch_california_housing()
house_price_dataset = sklearn.datasets.fetch_california_housing()

print(house_price_dataset.data)   #prints the input features of the dataset (like income, house age, number of rooms,...)
print(house_price_dataset.target) #prints the target values, which are the house prices that the model should predict.

print(house_price_dataset.head())

"""dataset is converted into dataframe ,to make data analysis, cleaning, and understanding the dataset much easier."""

house_price_dataframe = pd.DataFrame(house_price_dataset.data, columns = house_price_dataset.feature_names)

print(house_price_dataframe.head())

house_price_dataframe.columns = house_price_dataframe.columns.str.lower()

house_price_dataframe['houseage']

house_price_dataframe['houseage'].head()

if house_price_dataset.get('price') is not None:
    print("Column exists")
else:
    print("Column does not exist")

if house_price_dataset.get('houseage') is not None:
    print("Column exists")
else:
    print("Column does not exist")

if house_price_dataframe.get('MedInc') is not None:
    print("Column exists")
else:
    print("Column does not exist")

if house_price_dataframe.get('houseage') is not None:
    print("Column exists")
else:
    print("Column does not exist")

# Add the target as a new column called 'Price'
house_price_dataframe['Price'] = house_price_dataset.target

house_price_dataframe.head()

if house_price_dataframe.get('Price') is not None:
    print("Column exists")
else:
    print("Column does not exist")

# checking the number of rows and Columns in the data frame
house_price_dataframe.shape

# check for missing values
house_price_dataframe.isnull().sum()

# statistical measures of the dataset
house_price_dataframe.describe()

"""Understanding the correlation between various features in the dataset

Positive Correlation

Negative Correlation
"""

correlation = house_price_dataframe.corr()

# constructing a heatmap to nderstand the correlation
plt.figure(figsize=(10,10))
sns.heatmap(correlation, cbar=True, square=True, fmt='.1f', annot=True, annot_kws={'size':8}, cmap='Blues')

#Splitting the data and Target
X = house_price_dataframe.drop(['Price'], axis=1)
Y = house_price_dataframe['Price']

print(X)
print(Y)

#Splitting the data into Training data and Test data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 2)
print(X.shape, X_train.shape, X_test.shape)

"""# Model Training

**XGBoost** **Regressor**
"""

# loading the model
model = XGBRegressor()

#training the model with X_train
model.fit(X_train, Y_train)

"""**Evaluation**
Prediction on training data
"""

# accuracy for prediction on training data
training_data_prediction = model.predict(X_train)

print(training_data_prediction)

# R squared error
score_1 = metrics.r2_score(Y_train, training_data_prediction)

# Mean Absolute Error
score_2 = metrics.mean_absolute_error(Y_train, training_data_prediction)

print("R squared error : ", score_1)

"""Visualizing the actual Prices and predicted prices"""

plt.scatter(Y_train, training_data_prediction)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual Price vs Preicted Price")
plt.show()

"""Prediction on Test Data"""

#accuracy for prediction on test data
test_data_prediction = model.predict(X_test)

# R squared error
score_1 = metrics.r2_score(Y_test, test_data_prediction)

# Mean Absolute Error
score_2 = metrics.mean_absolute_error(Y_test, test_data_prediction)

print("R squared error : ", score_1)
print('Mean Absolute Error : ', score_2)